[build.environment]
    NPM_FLAGS="--version" # This makes netlify skip their automatic npm install, to let pnpm take care of it.

[build]
  functions="dist"

[dev]
  command = "pnpm run dev"
  targetPort = 9000
  port = 8080
  publish = "dist"
